steps:
  - label: ":gem: Build"
    command:
      - rake build
    plugins:
      - docker#v5.6.0:
          image: "ruby:3.2"

  - wait

  - label: ":rocket: :gem: :github:"
    key: "publish-gem"
    branches: "master"
    command:
      - ./.buildkite/setup_gem_credentials.sh
      - rake build
      - gem push --key github --host https://rubygems.pkg.github.com/Go-Shippit $(ls pkg/*.gem)
    plugins:
      - docker#v5.6.0:
          image: "ruby:3.2"
          environment:
            - GEM_CREDENTIALS
            - BUNDLE_RUBYGEMS__PKG__GITHUB__COM
